---
- name: update web servers
  hosts: web
  become: yes
  
  tasks:
  - name: ensure dapache is installed
    package:
      name: httpd
      state: present

  - name: ensure dapache is enabled
    service:
      name: httpd
      enabled: yes

  - name: ensure apache is started
    service:
      name: httpd
      state: started

... 
